### ISSUE TITLE
Unable to load HTML to Window after loadurl

### ISSUE THREAD

**Issue by vdayanand** [JunoLab/Blink.jl#150]
```
using Blink
w = window()

loadurl(w, "https://www.google.com")
body!(w, "Hello") ## this fails

```

Window console error
```
VM233:1 [Deprecation] 'webkitURL' is deprecated. Please use 'URL' instead.
(anonymous) @ VM233:1
(unknown) Uncaught ReferenceError: Blink is not defined
    at <anonymous>:1:1
    at EventEmitter.electron.ipcRenderer.on (/Users/vdayanan/.julia/dev/Blink/deps/Julia.app/Contents/Resources/electron.asar/renderer/web-frame-init.js:36:30)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
```

```
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)
```

**Comment by NHDaly** [comment]
Ah, yeah i can confirm this. The Developer Tools output contains the following error:

```js
Uncaught ReferenceError: Blink is not defined
    at <anonymous>:1:1
    at EventEmitter.electron.ipcRenderer.on (/Users/daly/.julia/dev/Blink/deps/Julia.app/Contents/Resources/electron.asar/renderer/web-frame-init.js:36)
    at emitMany (events.js:147)
    at EventEmitter.emit (events.js:224)
```

So the reason this doesn't work is that after loading the new URL, the page doesn't have the Blink javascript loaded anymore, so it isn't able to handle the request to update the page.
When you open a new window, by default Blink has that window load a default url, which talks to the webserver that Blink has set up, in order to load the default `main.html`, which ultimately loads the `blink.js`, needed for the content apis (`body!`, etc) to work.

You can force the window to re-load the default content, but you wont be able to communicate with javascript, though, I _think_ because you're reusing the websocket that was bound to the original javascript when you first loaded the page.. But just to see how that works, it's like this:

```julia
julia0.7> loadurl(w, "http://127.0.0.1:$(Blink.port[])/1")
>> false

julia0.7> Error handling websocket connection:
Future can be set only once
```

There's probably a better way to reset the Window that i don't know about, but if not, we should maybe consider adding one?

**Comment by pfitzseb** [comment]
We could also re-inject the Blink JS after the page has been loaded and open a new websocket, no?
