### ISSUE TITLE
Error memory leak when running blink on windows.

### ISSUE THREAD

**Issue by CVasquezG** [JunoLab/Blink.jl#74]
Whenever i try to run my julia script on Windows 10 I get this error:

`(node) warning: possible EventEmitter memory leak detected. 11 did-finish-load listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at EventEmitter.once (events.js:265:8)
    at EventEmitter.webContents.executeJavaScript (C:\Users\camil\.julia\v0.5\Blink\deps\atom\resources\atom.asar\browser\api\lib\web-contents.js:67:28)
    at eval (eval at <anonymous> (C:\Users\camil\.julia\v0.5\Blink\src\AtomShell\main.js:82:17), <anonymous>:1:18)
    at BrowserWindow.<anonymous> (C:\Users\camil\.julia\v0.5\Blink\src\AtomShell\main.js:82:12)
    at evalwith (C:\Users\camil\.julia\v0.5\Blink\src\AtomShell\main.js:83:6)
    at withwin (C:\Users\camil\.julia\v0.5\Blink\src\AtomShell\main.js:88:12)
    at eval (eval at <anonymous> (C:\Users\camil\.julia\v0.5\Blink\src\AtomShell\main.js:18:25), <anonymous>:1:1)
    at Object.handlers.eval (C:\Users\camil\.julia\v0.5\Blink\src\AtomShell\main.js:18:16)
    at line (C:\Users\camil\.julia\v0.5\Blink\src\AtomShell\main.js:46:26)` 

I dont get any of this when i run it on linux(ubuntu 16.04).
Some times everything works fine, it displays everything like on linux but most of the times it just opens a blank window where nothing happens.

**Comment by CVasquezG** [comment]
I just  tried to run my script multiple times and the only time it displayed something i got this error on the window console. 
![errorjs](https://cloud.githubusercontent.com/assets/8881142/19900936/88895ec6-a022-11e6-895e-ffd6732fcfb7.png)

**Comment by pfitzseb** [comment]
Can you give some more information about the script you're using?

**Comment by CVasquezG** [comment]
Issue lied on an infinite loop that i had on a julia file. The memory leak was easily fixed by using sleep(0.01) every iteration.
